[package]
name = "rust-metasploit"
version = "0.1.5"
authors = ["h4ck3r@parrot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq={ version="*",features=["json"] }
rmp-serde="0.13.7"
serde_json="*"
serde={ version="1.0.117" , features=["derive"]}
snafu="0.2.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[lib]
name="metasploit"

[net]  
git-fetch-with-cli = true
